const defaultUrl = 'http://localhost:3000/';
const url = defaultUrl;

const API_MASTERDATA_GET_ALL_ROLE = url + 'GetAllRole';
const API_MASTERDATA_POST_ROLE = url + 'CreateNewrtRole';
const API_MASTERDATA_UPDATE_ROLE = url + 'UpdateRole';
const API_MASTERDATA_GET_ALL_TABLE = url + 'GetAllTable';

const API_MASTERDATA_GET_ALL_USER = url + 'GetAllUser';
const API_MASTERDATA_GET_TABLE_BY_IDROLE = url + 'GetTableByIDRole';
const API_MASTERDATA_POST_USER = url + 'CreateNewUser';
const API_MASTERDATA_UPDATE_USER = url + 'UpdateUsers';

const API_MASTERDATA_GET_ALL_USER_PIC = url + 'GetAllUserPIC';
const API_MASTERDATA_GET_USER_PIC_BY_USERNAME = url + 'GetUserPICByUsername';
const API_MASTERDATA_CREATE_UPDATE_SUPPLIER_PIC = url + 'CreateUpdateSupplierPIC';
const API_MASTERDATA_GET_ALL_TAM_INV = url + 'GetAllTamInv';
const API_MASTERDATA_DELETE_SUPPLIER_TAMPIC_BY_ID = url + 'DeleteSupplierTAMPICById';
const API_MASTERDATA_GET_ALL_SUPPLIER_TAMPIC = url + 'GetAllSupplierTAMPIC';
const API_MASTERDATA_GET_TAM_INV_BY_CODE = url + 'GetTamInvByCode';
const API_MASTERDATA_CREATE_UPDATE_SUPPLIER_TAM_INV = url + 'CreateUpdateSupplierTamINV';


const API_MASTERDATA_GET_ALL_PATH = url + 'GetAllPath';
const API_MASTERDATA_POST_PATH = url + 'CreatePath';
const API_MASTERDATA_UPDATE_PATH = url + 'UpdatePath';

const API_MASTERDATA_GET_ALL_WORKFLOW = url + 'GetAllWorkFlow';
const API_MASTERDATA_POST_WORKFLOW = url + 'CreateWorkFlow';
const API_MASTERDATA_UPDATE_WORKFLOW = url + 'UpdateWorkFlow';
const API_MASTERDATA_GET_WORKFLOW_BY_ID = url + 'GetDetailWorkFlow';
const API_MASTERDATA_GET_PATH_BY_ROLE_END = url + 'GetPathByRoleEnd';
const API_MASTERDATA_UPDATE_WORKFLOW_DETAIL = url + 'UpdateWorkFlowPathDetail';

/* lOGISTIC */
const API_GET_MODEL_DATA = url + 'GetModelData';
const API_GET_YEAR_BY_MODEL = url + 'GetYearByModel';
const API_GET_TYPE_BY_YEAR_ID = url + 'GetTypeByYearId';
const API_GET_CATEGORY_BY_MANTAIN = url + 'GetCategoryMaintain';

const API_GENERATE_NEW_TICKET = url + 'GenerateNewTicket';
const API_LIST_INQUIRY_TICKET_ETD = url + 'ListInquiryTicketETD';
const API_GET_PART_NUMBER_DETAIL = url + 'GetPartNumberDetail';
const API_GET_ALL_CATEGORY = url + 'GetAllCategoryETD';
const API_CREATE_NEW_TICKET_ETD = url + 'CreateNewTicketETD';
const API_ANSWER_TICKET_ETD = url + 'TicketAnswer';
const API_ESCALATED_TICKET_ETD = url + 'TicketEskalasi';
const API_REJECT_TICKET_ETD = url + 'TicketReject';
const API_CANCEL_TICKET_ETD = url + 'TicketCancel';
const API_CLOSE_TICKET_ETD = url + 'TicketSurvei';
const API_GET_TICKET_ETD_DETAIL = url + 'GetTicketETDDetailByNoTicket';
const API_GET_TICKET_ETD_MONITORING_NOTES = url + 'GetTicketETDMonitorNotesByNoTicket';

const API_GET_LIST_INQUIRY_TICKET_PART = url + 'ListInquiryTicketPart';
const API_GET_TICKET_PART_DETAIL = url + 'GetTicketPartDetailByNoTicket';
const API_CREATE_NEW_TICKET_PART = url + 'CreateNewTicketPart';
const API_GET_TICKET_PART_MONITORING_NOTES = url + 'GetTicketPARTMonitorNotesByNoTicket';
const API_CANCEL_TICKET_PART = url + 'TicketCancel';
const API_REJECT_TICKET_PART = url + 'TicketReject';
const API_CLOSE_TICKET_PART = url + 'TicketSurvei';
const API_ANSWER_TICKET_PART = url + 'TicketAnswer';
const API_ESCALATED_TICKET_PART = url + 'TicketEskalasi';

const API_LIST_INBOX_TICKET_ETD = url + 'ListInboxTicketETD';
const API_LIST_SENT_TICKET_ETD = url + 'ListSentTicketETD';
const API_LIST_ARCHIVE_TICKET_ETD = url + 'ListArchiveTicketETD';

const API_LIST_INBOX_TICKET_PART = url + 'ListInboxTicketPart';
const API_LIST_SENT_TICKET_PART = url + 'ListSentTicketPart';
const API_LIST_ARCHIVE_TICKET_PART = url + 'ListArchiveTicketPart';

const API_MASTERDATA_GET_ALL_MODULE = url + 'GetAllModule';
const API_MASTERDATA_GET_MODULE_BY_ROLE = url + 'GetModulesByRoleId';

const API_GET_COUNT_TICKET = url + 'GetCountTicket';
const API_GET_DASHBOARD_ETD = url + 'GetDataDashboard';
const API_GET_DASHBOARD_PART = url + 'GetDataDashboardPart';
const API_GET_DASHBOARD_PRICE = url + 'GetDataDashboardPrice';
const API_GET_DASHBOARD_CLAIM = url + 'GetDataDashboardClaim';

const API_GET_TYPE_BY_YEAR = url + 'GetTypeByYearId';
const API_GET_CATEGORY_MAINTAIN = url + 'GetCategoryMaintain';

const API_CREATE_NEW_TICKET_PRICE = url + 'CreateNewTicketPrice';
const API_LIST_INQUIRY_TICKET_PRICE = url + 'ListInquiryTicketPrice';
const API_LIST_INBOX_TICKET_PRICE = url + 'ListInboxTicketPrice';
const API_LIST_SENT_TICKET_PRICE = url + 'ListSentTicketPrice';
const API_LIST_ARCHIVE_TICKET_PRICE = url + 'ListArchiveTicketPrice';
const API_CANCEL_TICKET_PRICE = url + 'TicketCancel';
const API_REJECT_TICKET_PRICE = url + 'TicketReject';
const API_CLOSE_TICKET_PRICE = url + 'TicketSurvei';
const API_ANSWER_TICKET_PRICE = url + 'TicketAnswer';
const API_ESCALATED_TICKET_PRICE = url + 'TicketEskalasi';

const API_GET_TICKET_PRICE_DETAIL = url + 'GetTicketPriceDetailByNoTicket';
const API_GET_TICKET_PRICE_MONITORING_NOTES = url + 'GetTicketPriceMonitorNotesByNoTicket';
const API_POST_UPLOAD_FILE = url + 'UploadFile';
const API_GET_SUPPLIER_CODE_BY_USER_ID = url + 'GetSupplierCodeByUserId';

const API_LOGIN_USERNAME = url + 'LoginUsername';
const API_LOGIN_TOKEN = url + 'LoginToken';

const Config = {
    API_MASTERDATA_GET_ALL_ROLE,
    API_MASTERDATA_GET_ALL_TABLE,
    API_MASTERDATA_POST_ROLE,
    API_MASTERDATA_UPDATE_ROLE,
    API_MASTERDATA_GET_ALL_USER,
    API_MASTERDATA_GET_TABLE_BY_IDROLE,
    API_MASTERDATA_POST_USER,
    API_MASTERDATA_UPDATE_USER,
    API_MASTERDATA_GET_ALL_PATH,
    API_MASTERDATA_POST_PATH,
    API_MASTERDATA_UPDATE_PATH,
    API_MASTERDATA_GET_ALL_WORKFLOW,
    API_MASTERDATA_POST_WORKFLOW,
    API_MASTERDATA_UPDATE_WORKFLOW,
    API_MASTERDATA_GET_WORKFLOW_BY_ID,
    API_MASTERDATA_GET_ALL_MODULE,
    API_MASTERDATA_GET_MODULE_BY_ROLE,
    API_MASTERDATA_GET_PATH_BY_ROLE_END,
    API_MASTERDATA_UPDATE_WORKFLOW_DETAIL,
    API_MASTERDATA_GET_ALL_USER_PIC,
    API_MASTERDATA_GET_USER_PIC_BY_USERNAME,
    API_MASTERDATA_CREATE_UPDATE_SUPPLIER_PIC,
    API_MASTERDATA_DELETE_SUPPLIER_TAMPIC_BY_ID,
    API_MASTERDATA_GET_ALL_SUPPLIER_TAMPIC,
    API_MASTERDATA_GET_ALL_TAM_INV,
    API_MASTERDATA_GET_TAM_INV_BY_CODE,
    API_MASTERDATA_CREATE_UPDATE_SUPPLIER_TAM_INV,
    API_GENERATE_NEW_TICKET,
    API_GET_PART_NUMBER_DETAIL,
    API_GET_ALL_CATEGORY,
    API_CREATE_NEW_TICKET_ETD,
    API_ANSWER_TICKET_ETD,
    API_REJECT_TICKET_ETD,
    API_ESCALATED_TICKET_ETD,
    API_CANCEL_TICKET_ETD,
    API_CLOSE_TICKET_ETD,
    API_LIST_INQUIRY_TICKET_ETD,
    API_LIST_INBOX_TICKET_ETD,
    API_GET_TICKET_ETD_DETAIL,
    API_GET_TICKET_ETD_MONITORING_NOTES,
    API_LIST_SENT_TICKET_ETD,
    API_LIST_ARCHIVE_TICKET_ETD,
    API_GET_COUNT_TICKET,
    API_GET_DASHBOARD_ETD,
    API_GET_DASHBOARD_PART,
    API_GET_DASHBOARD_PRICE,
    API_GET_DASHBOARD_CLAIM,
    API_GET_MODEL_DATA,
    API_GET_YEAR_BY_MODEL,
    API_GET_TYPE_BY_YEAR,
    API_GET_CATEGORY_MAINTAIN,
    API_CREATE_NEW_TICKET_PRICE,
    API_LIST_INQUIRY_TICKET_PRICE,
    API_LIST_INBOX_TICKET_PRICE,
    API_LIST_SENT_TICKET_PRICE,
    API_LIST_ARCHIVE_TICKET_PRICE,
    API_GET_TICKET_PRICE_DETAIL,
    API_GET_TICKET_PRICE_MONITORING_NOTES,
    API_CREATE_NEW_TICKET_PART,
    API_GET_TYPE_BY_YEAR_ID,
    API_GET_CATEGORY_BY_MANTAIN,
    API_GET_LIST_INQUIRY_TICKET_PART,
    API_GET_TICKET_PART_DETAIL,
    API_GET_TICKET_PART_MONITORING_NOTES,
    API_CANCEL_TICKET_PART,
    API_REJECT_TICKET_PART,
    API_CLOSE_TICKET_PART,
    API_ANSWER_TICKET_PART,
    API_ESCALATED_TICKET_PART,
    API_ANSWER_TICKET_PRICE,
    API_REJECT_TICKET_PRICE,
    API_ESCALATED_TICKET_PRICE,
    API_CANCEL_TICKET_PRICE,
    API_CLOSE_TICKET_PRICE,
    API_LIST_INBOX_TICKET_PART,
    API_LIST_SENT_TICKET_PART,
    API_LIST_ARCHIVE_TICKET_PART,
    API_POST_UPLOAD_FILE,
    API_GET_SUPPLIER_CODE_BY_USER_ID,
    API_LOGIN_USERNAME,
    API_LOGIN_TOKEN,
};

export default Config;
